# Generated by Django 5.0.1 on 2024-02-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_column_board_alter_subtask_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtask',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
